### ISSUE TITLE
Account linking

### ISSUE THREAD

**Issue by ElisaLecluse** [actions-on-google/assistant-conversation-testing-nodejs#11]
Is there a way to use this Testing Library when the project uses [account linking](https://developers.google.com/assistant/identity/google-sign-in) (we use Dialogflow ES instead of Actions Builder, which calls our Node.js application via a webhook)? 
Our intents can only be tested when the user's account is linked.

Thanks in advance!

**Comment by Fleker** [comment]
This library does not work with Actions Builder.

Edit: I made a mistake. I meant to say it either does not work with Dialogflow, or works only with Actions Builder.

**Comment by ElisaLecluse** [comment]
But I said we do not use Actions Builder? It works well with Dialogflow.

Our question is how we can [link a user's account to the Google Assistant](https://developers.google.com/assistant/identity/google-sign-in) when **testing** the intents with this library.

**Comment by Jelle-elaut** [comment]
@Fleker can you check this question again please? The question is not about Actions Builders, we need OAuth authorization for all our intents. Thanks!

**Comment by Fleker** [comment]
I apologize for my earlier mistake. I meant that this testing does not work with Dialogflow, and works only with Actions Builder. So I don't expect that this is feasible.
