### ISSUE TITLE
Always retrieves null from sessionStorage parameters

### ISSUE THREAD

**Issue by kekkox** [actions-on-google/assistant-conversation-testing-nodejs#14]
# The problem

I have founded a bug which prevents getting the parameters from the session with the `getSessionParam` function.

When i call the `getSessionParam` function in this way:

```js
testManager.getSessionParam("MY_PARAM");
```

I always get null as result, even if the param actually exists into session.

## What I found out

Actually, the sessionStorage object is the following: 

```js
sessionStorage: {
    fields: {
         // Your session params     
    }
}
```

But you are trying to access to the fields in this way:

```js
sessionStorage[name]
```

The correct way should be:
```js
sessionStorage.fields[name]
```

This bug affect also the `assertSessionParam` function.

Hope that it will help you to improve this great tool 😬

**Comment by Fleker** [comment]
This suggests the object does not match the [expected mocked response](https://github.com/actions-on-google/assistant-conversation-testing-nodejs/blob/master/src/test/mock-response1.json#L165).

**Comment by Fleker** [comment]
The [API reference](https://developers.google.com/assistant/actions/api/reference/rest/v2/projects/sendInteraction#executionstate) suggests the type should be a simple map. Is that not what you're seeing?

**Comment by kekkox** [comment]
I don't know if it is only a my problem, but what I retrieve (basing my example the expected mocked response) is something like this:

```js
{
    sessionStorage: {
        fields: {
            categoryType: { stringValue: "cats", kind: "stringValue" },
            currentFactsData: {
                structData: {
                    title: { stringValue: "Fact fake title", kind: "stringValue" }
                },
                kind: "structData"
            }
        }
    }
}
```

**Comment by Fleker** [comment]
After some followup, it seems like the type we define for [sessionStorage](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Struct) needs to be updated. User and Home storages are similarly affected.

**Comment by Fleker** [comment]
The [underlying proto / TS definition](https://raw.githubusercontent.com/actions-on-google/assistant-actions-nodejs/8123f505b7e3ff4895aed354146593906d3f2f44/protos/protos.d.ts) is correct:

```
/** Properties of an ExecutionState. */
                interface IExecutionState {

                    /** ExecutionState currentSceneId */
                    currentSceneId?: (string|null);

                    /** ExecutionState sessionStorage */
                    sessionStorage?: (google.protobuf.IStruct|null);

                    /** ExecutionState slots */
                    slots?: (google.actions.sdk.v2.ISlots|null);

                    /** ExecutionState promptQueue */
                    promptQueue?: (google.actions.sdk.v2.conversation.IPrompt[]|null);

                    /** ExecutionState userStorage */
                    userStorage?: (google.protobuf.IStruct|null);

                    /** ExecutionState householdStorage */
                    householdStorage?: (google.protobuf.IStruct|null);
                }
```

Perhaps the mocked response just needs to be typed for extra validation (and code changes to ensure unit tests are correct).

**Comment by kyngvesson** [comment]
Any update on this issue? We solved this temporaraly by overriding the functions on test manager and decoding the stuct. This can also be done for user and home storage. Example:
```
    testManager = new ActionsOnGoogleTestManager({ projectId: PROJECT_ID })

    testManager.getSessionParam = function (name) {
      const executionState = this.getExecutionState(this.getLatestResponse())
      if (executionState &&
        'sessionStorage' in executionState &&
        executionState.sessionStorage) {
        const sessionStorage = struct.decode(executionState.sessionStorage)
        if (sessionStorage && name in sessionStorage) {
          return sessionStorage[name]
        }
      }
    }
```

Note: this requires the **pb-util** npm package.
