### ISSUE TITLE
Is there a way to use other authentication method apart from service account json?

### ISSUE THREAD

**Issue by kkocel** [actions-on-google/assistant-conversation-testing-nodejs#16]
Using service account json is a bit problematic since it requires storing json file in the repository in order to make tests work out of box. Maybe there could be other way to authenticate - eg. api key?

**Comment by Fleker** [comment]
You can embed the `GOOGLE_APPLICATION_CREDENTIALS` in an environment variable and have each person setup their own locally by putting the path in `.gitignore`.

There's plenty of documentation on the [best way to secure credentials](https://cloud.google.com/docs/authentication/best-practices-applications) depending on your use-case. That may be a good place to learn more.

**Comment by vicly** [comment]
Thank you @kkocel and @Fleker for the response.

The background is that we run tests in the CICD agent, so yes, we store credentials in Git repo securely.

About the credentials, @Fleker's solution definitely works, which is what we're doing right now. But for `GOOGLE_APPLICATION_CREDENTIALS`
1. it's Google user specific, have to create a dedicated user for CICD => internal process + extra user management
2. generating credentials is a manual process by running `gaction login`, not sure how to automate it => automation is key
2. per testing, `gaction login` invalidates previous credentials => a risky point about human error

So, it'll be great If the non-user-specific credentials are supported by this testing library, e.g. service account, API key, etc.

**Comment by vicly** [comment]
Hi @kkocel, could you share how you use the service account json generated in GCP console? Thanks.

Our case is that we want to run tests in the CICD agent which needs some stable credentials.

`GOOGLE_APPLICATION_CREDENTIALS` definitely works, which is what we're doing right now, but:
1. it's Google user specific, have to create a dedicated user for CICD => internal process + extra user management
2. generating credentials is a manual process by running `gaction login`, not sure how to automate it => automation is key
2. per testing, `gaction login` invalidates previous credentials => a risky point about human error

So, it'll be great If the non-user-specific credentials are supported by this library, e.g. service account, API key, etc.
